# Generated by Django 2.0.5 on 2018-07-18 04:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=70)),
                ('faculty', models.CharField(max_length=70)),
                ('level', models.CharField(max_length=70)),
                ('health_issues', models.CharField(max_length=300)),
                ('sex', models.CharField(max_length=20)),
                ('self_description', models.CharField(max_length=700)),
                ('study', models.CharField(max_length=70)),
                ('kin_name', models.CharField(max_length=70)),
                ('kin_phone', models.CharField(max_length=70)),
                ('user', models.OneToOneField(on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
