# Generated by Django 2.0.5 on 2018-07-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0002_auto_20180718_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lodge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='lodge',
            name='zone',
            field=models.ForeignKey(on_delete='models.CASCADE', to='lodges.Zone'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lodge',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.CASCADE', to='lodges.Lodge'),
        ),
    ]
