# Generated by Django 2.0.5 on 2018-07-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0003_auto_20180718_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodge',
            name='price',
            field=models.IntegerField(default=60000),
        ),
    ]
