# Generated by Django 2.0.5 on 2018-07-20 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0005_zone_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='lodge',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
